server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    redis:
      # ✅ 本地访问，速度最快，最安全
      host: 127.0.0.1
      port: 6379
      password: "Maria%@)1314"
      database: 1
  servlet:
    multipart:
      max-file-size: 10MB       # 单个文件最大 10MB
      max-request-size: 10MB    # 整个请求最大 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    # ✅ 数据库必须本地访问
    url: jdbc:postgresql://127.0.0.1:5432/inventory_store
    username: inventory_user
    password: SJNreZr6rxyT

logging:
  level:
    com.inventory.mapper: debug

app:
  cors:
    # ✅ 前端访问地址
    allowed-origins: http://120.53.88.204
  upload:
    avatar-path: /opt/upload/avatar/