# ==============================
# gateway-service · 公共配置
# 环境切换：spring.profiles.active = dev | prd
# ==============================
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
        - id: platform-upload
          uri: lb://platform-service
          predicates:
            - Path=/upload/**
          filters:
            - RewritePath=/upload/(?<segment>.*), /api/upload/${segment}
        - id: platform-service
          uri: lb://platform-service
          predicates:
            - Path=/api/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
