# ==============================
# order-service · 公共配置
# ==============================
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        prefer-ip-address: true
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        file-extension: yaml
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
  config:
    import:
      - optional:nacos:order-service.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/inventory_store
    username: inventory_user
    password: ${DB_PWD:}

server:
  port: 8083
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

app:
  nacos-demo-message: local-default
  sentinel:
    order-ping-flow-enabled: true
    order-unstable-degrade-enabled: true
    order-business-flow-enabled: true
    order-create-qps: 20
    order-cancel-qps: 20
    inventory-degrade-enabled: true

logging:
  level:
    root: INFO
    com.inventory.order: INFO
    com.inventory.modules.order: INFO
    com.alibaba.cloud.nacos: INFO
