# order-service · 服务器生产
spring:
  datasource:
    password: ${DB_PWD}
  cloud:
    sentinel:
      eager: false
      transport:
        dashboard: 127.0.0.1:8858

logging:
  level:
    root: INFO
    com.inventory: INFO
